apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config
data:
  root-password: {{ .Values.mysql.rootPassword | quote }}
  user-password: {{ .Values.mysql.password | quote }}
